# Generated by Django 6.0.2 on 2026-02-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_categoria_remove_post_imagen_url_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Una frase corta que enganche al lector.', max_length=300, null=True),
        ),
    ]
