# Generated by Django 6.0.2 on 2026-02-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_post_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Breve explicación de para qué sirve.')),
                ('enlace', models.URLField()),
                ('categoria', models.CharField(choices=[('VERIFICACION', 'Verificación y Análisis (Externo)'), ('GUIAS', 'Guías oficiales y Kits (Externo)'), ('EXCLUSIVO', 'Recursos Exclusivos HDS')], default='VERIFICACION', max_length=20)),
                ('icono', models.CharField(default='bi-link-45deg', help_text='Código del icono Bootstrap (ej: bi-shield)', max_length=50)),
                ('orden', models.IntegerField(default=0, help_text='Número bajo sale antes')),
            ],
            options={
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
