# Generated by Django 6.0.2 on 2026-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Miniatura de la web o recurso', null=True, upload_to='recursos/thumbnails/'),
        ),
    ]
