# Generated by Django 6.0.2 on 2026-02-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_recurso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Sube un manual o guía en PDF', null=True, upload_to='recursos/pdfs/'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='enlace',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
